# config.yaml
optimizer_params:
  - name: muon
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    weight_decay: 0
    lr_schedule: constant

  - name: muon-nonlmo
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    weight_decay: 0
    lr_schedule: constant

  - name: muon-l2_prod
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    weight_decay: 0
    lr_schedule: constant

  - name: muon-nonlmo-l2_prod
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    weight_decay: 0
    lr_schedule: constant

  - name: muon-rms
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    weight_decay: 0
    lr_schedule: constant

  - name: muon-nonlmo-rms
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    weight_decay: 0
    lr_schedule: constant

  - name: muon-l2_prod-rms
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    weight_decay: 0
    lr_schedule: constant

  - name: muon-nonlmo-l2_prod-rms
    lr: [0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
    weight_decay: 0
    lr_schedule: constant

training_params:
  tokens_processed: 2048 # 2^11  # 524288 # 2^19
  val_tokens_processed: 8388608 #2^23
  batch_size: 2
  num_epochs: 1
  context_length: 512
  gradnorm: 1.0
  tensorcore_precision: high   #Can be highest, high, or medium
  autocast: True
  mixed_precision: bfloat16
  compile: True

logging_params:
  val_tokens_processed: 2048 #2^23
  log_step: 50
  val_step: 50
  save_ckpt_step: 500
  load_ckpt_step: 0
  keep_last: 2
  ckpt_dir: "" #/mnt/ceph/users/cmodi/gptopt/
  

gpt_model:
  n_embd: 768    
  n_layer: 12   
  n_head: 12    
  vocab_size: 50257
  flash_attention: True

dataset:
  name: "tiny_shakespeare"  
